### ISSUE TITLE
Apostrophes/single quotes not handled

### ISSUE THREAD

**Issue by buzzlight** [gtalarico/airtable-python-wrapper#11]
https://github.com/gtalarico/airtable-python-wrapper/blob/484f42edcabc0808880bd67b55cd1804161f0cfe/airtable/airtable.py#L581

This is an issue when for example searching for a name like "O'Brien".  The apostrophe in the name "closes" the apostrophe in the query and airtable throws an error.  In my local copy I just if'd my way around the problem, but it smells like there should be a more elegant way to handle this.

**Comment by gtalarico** [comment]
Interesting. Thanks for the suggestion.
Per the airtable documentation, I think single and double quotes need to be escaped with a backslash. 
Maybe we can add a simple regex replacement that replaces unescaped quotes with /' and /"

**Comment by aracnid** [comment]
It's easy enough to escape the input field value **_before_** it is passed into the function.
```
val_escaped = val.replace("'", r"\'")
```

**Comment by peterkaminski** [comment]
An intermediate fix would be to add a note to the documentation regarding escaping quotes in field values.

Interestingly, I had this problem with `table.match()` and a single quote, but a subsequent `table.insert()` with the same field value worked out _without_ escaping the single quote.

Just in case someone is searching for an example of the error message caused by an unescaped single quote, this is what I got -- basically "Invalid formula."

    requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/appqXJzYCDQgExxDC/Actors?filterByFormula={Name}='Ryan+O'Neal' (Decoded URL) [Error: {'type': 'INVALID_FILTER_BY_FORMULA', 'message': 'The formula for filtering records is invalid: Invalid formula. Please check your formula text.'}]

**Comment by gtalarico** [comment]
I think #120 fixes this - feel free to reopen otherwise
