### ISSUE TITLE
Fields without values are missing entirely when calling get_all()

### ISSUE THREAD

**Issue by Apreche** [gtalarico/airtable-python-wrapper#30]
Imagine I have a table with two columns named `id` and `name`. There is only one row in the table. The value of `id` is `1`. The value of `name` is completely blank. 

I make a call to `get_all()`. The call is successful. The return value looks like this:

```
>>> airtable.get_all()                                                             
[{'fields': {'id': 1}, 'createdTime': '2019-04-04T18:18:23.000Z', 'id': '***'}]
```

I expect the return value to look like this:

```
>>> airtable.get_all()                                                             
[{'fields': {'id': 1, 'name': None}, 'createdTime': '2019-04-04T18:18:23.000Z', 'id': '***'}]
```
Every single column should be present in every single row returned, whether that column has a value or not. 
I am aware that this could be a flaw in the airtable API, and not a bug in this Python module. If that is the case, feel free to close this bug and let me know.

**Comment by gtalarico** [comment]
Hi and thanks for posting the issue @Apreche  

This is "by design" - from the docs:
> Returned records do not include any fields with "empty" values, e.g. "", [], or false.

I don't necessarily like it, but it's a common pattern and the recommended API behavior 
by the Google JSON style guide:
https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Empty/Null_Property_Values#Empty/Null_Property_Values

The pattern it's particularly annoying with airtable because there is no way to fetch all available columns (table schema), but there is nothing that can be done on the client side since it can't know the schema either.

**Comment by Apreche** [comment]
Thanks! That is very annoying because fetching the list of all available columns is exactly what I need to do!

**Comment by gtalarico** [comment]
One workround I have used it to include a "hidden" column in each table with dummy, non-false values.
This row can be hidden from all views by having eg. Field `Dummy: True` or `IsSchema: True`
You can fetch this record when needed to get all field names and types but otherwise filter it out.
You could even have the field values be the python type names 
so you can cast types and get default values.

Very hacky and not recommended but you can use it if you are deseperate.
