### ISSUE TITLE
Implement append_by_field

### ISSUE THREAD

**Issue by samgdf** [gtalarico/airtable-python-wrapper#6]
This wrapper is amazing, fantastic, incredibly useful. Thank you.

Is it possible to append an update to not overwrite the content in a table cell, but rather add it to the beginning or end of a cell?

Cheers.

**Comment by gtalarico** [comment]
You are welcome @samgdf 

I think the append use case is too specific to be part of what is currently a light-weight Rest API wrapper.
I would rather keep it somewhat mapped to the functionalities provided by API.
Otherwise, what would be next? Append? Prepend? InsertAtIndex? Search and replace? Regex Search? 
all string operations? Hard to draw a line.
Does that make sense?

I think a functionality like prepend is better handled by the user. 
You can always make a simple function to accomplish the task:
1. Get all records.
2. Make the modifications to the data (ie append)
3. Use Mirror or Update calls to update the data

**Comment by samgdf** [comment]
Fair enough. Would you happen to know how to use your wrapper to mark a checkmark in airtable? I've tried update_by_field : true (shorthanding, but with validly formatted code), but it does not work.

Thanks again!

**Comment by gtalarico** [comment]
Should work if you just pass a python boolean. Let me know if doesn't work

**Comment by samgdf** [comment]
`(data[i]['fields']['checkedAT']) = True` does not work, for the field checkedAT, which is a check box.
